import type { LocalizedText } from "@/content";
type Section={title:LocalizedText;body:LocalizedText};
export const information:Record<"privacy"|"terms",{title:LocalizedText;sections:Section[]}>={
privacy:{title:{en:"Privacy",ar:"الخصوصية"},sections:[
{title:{en:"Contact and information",ar:"التواصل والبيانات"},body:{en:"Nabta is operated by Nour Abulnasr in Cairo, Egypt. Contact nourabulnasr@gmail.com about your information. Cal.com collects your name, email and business answers for consultations. Email and WhatsApp messages stay in those services. When enabled, the student library uses your email, account identifier, payment reference and lesson access to provide recordings. Never send card numbers, banking passwords or an InstaPay PIN.",ar:"نبتة بإدارة نور أبو النصر في القاهرة، مصر. تواصل على nourabulnasr@gmail.com بخصوص بياناتك. Cal.com بيجمع اسمك وبريدك وإجابات نشاطك لحجز الاستشارات. رسائل البريد وواتساب بتفضل في الخدمات دي. مكتبة الطالب عند تفعيلها بتستخدم بريدك ومعرّف الحساب ورقم التحويل وصلاحيات الدروس لتوفير التسجيلات. ما تبعتش أرقام البطاقات أو كلمات مرور البنك أو الرقم السري لإنستاباي."}},
{title:{en:"Connected services",ar:"الخدمات المتصلة"},body:{en:"Cloudflare hosts the site and processes connection information for delivery and security. Cal.com and Google handle booking and meetings. InstaPay processes transfers in its own app. The student library, when enabled, uses Supabase for sign-in and records, and Supabase or Cloudflare R2 for private media. Providers may process data outside Egypt under their own policies.",ar:"Cloudflare بيستضيف الموقع وبيعالج معلومات الاتصال للتشغيل والأمان. Cal.com وGoogle للحجز والاجتماعات. إنستاباي بيعالج التحويل في تطبيقه. مكتبة الطالب عند تفعيلها بتستخدم Supabase للدخول والسجلات، وSupabase أو Cloudflare R2 للملفات الخاصة. مقدمو الخدمات ممكن يعالجوا البيانات خارج مصر وفق سياساتهم."}},
{title:{en:"Cookies and your choices",ar:"ملفات الارتباط واختياراتك"},body:{en:"The public site uses no advertising cookies or behavioural analytics. Student sign-in uses essential session cookies when enabled; sign out to end the website session. Contact us for access, correction or deletion of your data. We may verify your identity. We retain account and purchase records to provide access, resolve disputes and meet legal duties; some records cannot be deleted immediately. Under-18s should involve a parent or guardian. Do not put sensitive personal documents in booking answers.",ar:"الموقع العام مش بيستخدم ملفات إعلانات أو تحليلات سلوكية. دخول الطالب بيستخدم ملفات جلسة ضرورية عند تفعيله؛ سجّل خروج لإنهاء الجلسة. تواصل لطلب نسخة أو تصحيح أو حذف بياناتك، وقد نتحقق من هويتك. بنحتفظ بسجلات الحساب والشراء لتوفير الوصول وحل النزاعات والالتزامات القانونية؛ بعض السجلات ما ينفعش تتحذف فورًا. أقل من ١٨ سنة يشاركوا ولي الأمر. ما تحطش مستندات شخصية حساسة في إجابات الحجز."}}
]},
terms:{title:{en:"Services and learning terms",ar:"شروط الخدمات والتعلّم"},sections:[
{title:{en:"Business consultations",ar:"استشارات الشركات"},body:{en:"A free 30-minute Google Meet call, daily 5pm–midnight Cairo time, booked at least 24 hours ahead. Provide your business idea, goals and gaps. Any implementation is separately scoped and quoted. Use the change/cancel options in your Cal.com confirmation if you cannot attend.",ar:"مكالمة Google Meet مجانية لمدة ٣٠ دقيقة، يوميًا ٥ مساءً لمنتصف الليل بتوقيت القاهرة، بالحجز قبلها بـ٢٤ ساعة على الأقل. وضّح فكرتك وأهدافك واحتياجاتك. أي تنفيذ بنطاق وسعر منفصل. لو مش هتحضر استخدم تغيير أو إلغاء الموعد في تأكيد Cal.com."}},
{title:{en:"Live and recorded lessons",ar:"الدروس المباشرة والمسجلة"},body:{en:"Live tutoring and recordings are separate purchases, each EGP 250 per session. Confirm live format, place and time with Nour before paying. The planned recorded course has 20 lessons of about 1–2 hours: EGP 250 each or EGP 4,500 for all 20. Do not pay for recordings until they are published as available. Purchased recordings have lifetime personal access with no scheduled expiry.",ar:"الدروس المباشرة والتسجيلات مشتريات منفصلة، وسعر الحصة في كل خيار ٢٥٠ جنيه. أكّد الطريقة والمكان والموعد مع نور قبل دفع الدرس المباشر. الكورس المسجل المخطط ٢٠ درسًا، حوالي ساعة لساعتين لكل درس: ٢٥٠ جنيه للدرس أو ٤٥٠٠ للعشرين. ما تدفعش للتسجيلات إلا لما تظهر متاحة. التسجيلات المشتراة بوصول شخصي دائم من غير موعد انتهاء محدد."}},
{title:{en:"Payment and access",ar:"الدفع والوصول"},body:{en:"Check the InstaPay recipient before confirming a transfer. Submit its reference for manual verification. A request does not prove payment or unlock access automatically. Do not share accounts, redistribute or resell recordings. Verified misuse may lead to access revocation. Protection reduces sharing but cannot guarantee prevention of downloads or screen capture.",ar:"راجع مستلم إنستاباي قبل تأكيد التحويل. ابعت رقم العملية للمراجعة اليدوية. تقديم الطلب مش إثبات دفع ومش بيفعّل الوصول تلقائيًا. ما تشاركش الحساب أو تعيد توزيع أو بيع التسجيلات. إساءة الاستخدام المثبتة ممكن تؤدي لإلغاء الوصول. الحماية بتقلل المشاركة لكن مش بتضمن منع التنزيل أو تصوير الشاشة."}},
{title:{en:"Refunds, support and young learners",ar:"الاسترداد والدعم والطلاب الأصغر"},body:{en:"Our intended policy is no change-of-mind refunds after recording access is supplied, except where applicable law requires otherwise. Rights concerning non-delivery, defective service, duplicate payments and mandatory consumer protections remain. Contact nourabulnasr@gmail.com or WhatsApp +20 106 904 6666 for payment or access problems and lesson questions. Live-session changes are agreed before payment; no automatic cancellation fee is stated here. Under-18s should involve a parent or guardian. No particular grade or business result is promised.",ar:"سياستنا المقصودة عدم الاسترداد لتغيير الرأي بعد توفير التسجيل، إلا لو القانون يفرض غير ذلك. الحقوق المتعلقة بعدم التسليم أو عيب الخدمة أو الدفع المكرر والحماية الإلزامية للمستهلك محفوظة. تواصل على nourabulnasr@gmail.com أو واتساب +20 106 904 6666 لمشاكل الدفع والوصول وأسئلة الدروس. تغييرات الدروس المباشرة بتتفق عليها قبل الدفع؛ مفيش رسم إلغاء تلقائي معلن هنا. أقل من ١٨ سنة يشاركوا ولي الأمر. مفيش وعد بدرجة أو نتيجة تجارية محددة."}}
]}};
